services:
  frontend:
    build: .
    container_name: inventario-frontend
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    restart: unless-stopped
